USERNAME                   = 'nm480'
LOCATION                   = 'local'
LOCAL_TO_REMOTE_KEY_FILE   = '/homes/mlghomes/nm480/.ssh/nm480local2fear'
REMOTE_TO_LOCAL_KEY_FILE   = '/users/nm480/.ssh/nm480fear2local'
REMOTE_TEMP_PATH           = '/users/nm480/temp'
REMOTE_SCRATCH_PATH        = '/scratch'
REMOTE_PYTHON_PATH         = '/users/jrl44/python'
REMOTE_MATLAB_PATH         = '/users/jrl44/matlab'
REMOTE_MATLAB              = '/usr/local/apps/matlab/matlabR2013b/bin/matlab'
LOCAL_TEMP_PATH            = '/tmp'
LOCAL_HOST                 = 'sagarmatha'
LOCAL_MATLAB               = '/misc/apps/matlab/matlabR2013b/bin/matlab'

REMOTE_GPML_PATH = '/users/jrl44/GPML'
LOCAL_GPML_PATH = 'I am not set'
